interface=wlan0
bind-interfaces
dhcp-authoritative

domain=wifi-ap.local
dhcp-range=10.70.2.50,10.70.2.150,255.255.255.0,12h
dhcp-option=option:router,10.70.2.1
dhcp-option=option:dns-server,10.70.2.1

resolv-file=/run/systemd/resolve/resolv.conf
domain-needed
bogus-priv
